// app/utils/depoimentos.js

export const listaDepoimentos = [
  {
    id: 1,
    text: 'Conheci a Dra. por um outro advogado, então após levar a ela a minha demanda, com toda atenção ela me ouviu e prontamente me solicitou as provas, logo em seguida deu entrada na documentação. Um ponto importante a se destacar, me manteve atualizado de tudo.',
    author: 'Diogo Santos',
    role: 'Avaliação no Google',
  },
  {
    id: 2,
    text: 'Excelente profissional, muito educada, paciente tirou todas minhas duvidas, e fez o impossível no meu processo, então não poderia ter encontrado uma profissional melhor, e o cuidado e dedicação dela fizeram toda a diferença, muito grata pelo acolhimento e profissionalismo, Recomendo de olhos fechados!🙏🏽',
    author: 'Maria Ines',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 3,
    text: 'Bom dia!! Sem sombra alguma pra dúvidas! Yasmim Santana, embora tão jovem, mas detém um conhecimento versos dedicação com integridade q me faz acreditar que é e será uma das melhores advogada que eu já trabalhei! Parabéns Yasmin, continue sempre assim.',
    author: 'Josue Almeida',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 4,
    text: 'A melhor advogada, disposta, inteligente, solícita. Extremamente responsável em atender as necessidades individuais de cada cliente! Confio demais no seu trabalho!! Sucesso',
    author: 'Kelly Maiana Ivo da Cruz',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 5,
    text: 'Profissional excelente! Gostei muito do trabalho dela.',
    author: 'Gleidiane Lisboa Miranda',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 6,
    text: 'Excelente profissional, atenciosa, dedicada e muito esclarecedora. Gratidão Dra. Yasmin. Deus abençoe 🙌🏻',
    author: 'Joiza Santana',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 7,
    text: 'Me faltam elogios para falar desta profissional. Uma advogada disposta a ir até o fim por uma causa. Alguém muito humana e empatica ao qual serei sempre grata.',
    author: 'Maria Deodato',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 8,
    text: 'Uma excelente profissional, muito competente com seu trabalho, muito inteligente. Amamos o atendimento e trabalhamos dessa profissional! Resultado melhor que esperávamos !',
    author: 'Laiane Braga',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 9,
    text: 'Altamente competente e resolutiva. Sempre que solicitada, é muito clara e objetiva. Só elogios para um serviço de qualidade e eficiência.',
    author: 'Larissa Souza',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 10,
    text: 'Excelente advogada, sempre atenciosa e uma profissional incrível!',
    author: 'Josilene Carvalho',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 11,
    text: 'Gostei muito do trabalho dela, bem atenciosa e eficaz no que faz, amei ♥️',
    author: 'Thays Xavier',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 12,
    text: 'Excelente profissional... atenciosa e comprometida. Está de parabéns!!!',
    author: 'Adriana Lima',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 13,
    text: 'Muito competente, atenciosa, empática e prestativa. Atendimento impecável.',
    author: 'Alexsandra Santana',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 14,
    text: 'Profissional excelente, super atenciosa e competente.',
    author: 'Mylena De souza',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 15,
    text: 'Excelente profissional ❤️',
    author: 'Thamiris caroline',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 16,
    text: 'Simplesmente maravilhosa !',
    author: 'Elizabete da Cunha André Loyola',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 17,
    text: 'Perfeita ❤️',
    author: 'Caroline Gomes',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 18,
    text: 'Excelente atendimento e profissionalismo! Orienta o cliente desde o primeiro contato, com explicações claras e muita transparência em todo o processo. Sinônimo de compromisso e transparência!!',
    author: 'Tereza Cruz',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 19,
    text: 'Atendimento excelente e muito profissional. Recomendo fortemente!',
    author: 'Maria Amaral',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 20,
    text: 'Ótima advogada, muito dedicada e atenciosa com os detalhes do caso.',
    author: 'Selma Brandão',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 21,
    text: 'Serviço de alta qualidade e muita transparência. Super recomendo.',
    author: 'Illa Bastos',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 22,
    text: 'Profissionalismo e competência ímpares. Excelente atendimento do início ao fim.',
    author: 'Thiago Ramos dos S.Santana',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 23,
    text: 'Muito atenciosa e resolutiva, uma excelente profissional em quem você pode confiar.',
    author: 'Pamile silva Teles',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 24,
    text: 'Ótimo atendimento, advogada muito competente e empática com a nossa situação.',
    author: 'Isabel Gomes',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=150&h=150&auto=format&fit=crop',
  },
  {
    id: 25,
    text: 'Excelente profissional! A Dra. Yasmin foi ótima e super prestativa no meu caso de direito do consumidor. Me orientou em cada etapa com muita clareza, transparência e resolveu meu problema com enorme eficiência. Recomendo demais o seu trabalho.',
    author: 'Plínio de Lima',
    role: 'Avaliação no Google',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&h=150&auto=format&fit=crop',
  }
];
